name: Semgrep Collector for Wiz

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 19 20 * * *

jobs:
  collector:
    runs-on: ubuntu-latest

    env:
      MODE: agent
      WIZ_API_ENDPOINT: https://api.us36.app.wiz.io/graphql
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
      SEMGREP_DEPLOYMENT: danmolz
      TARGET_REPO: DanMolz/wiz-code-gha-demo

    container:
      image: danielmoloney/wiz-semgrep-connector

    steps:
    - run: echo "Running Wiz Semgrep Connector"