on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 19 20 * * *
name: Semgrep Collector for Wiz
jobs:
  collector:
    name: collector/ci
    runs-on: ubuntu-20.04
    env:
      MODE: agent
      WIZ_API_ENDPOINT: https://api.<region>.app.wiz.io/graphql
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
      SEMGREP_API_TOKEN: ${{ secrets.SEMGREP_API_TOKEN }}
      SEMGREP_DEPLOYMENT: your_semgrep_deployment
    container:
      image: danielmoloney/wiz-semgrep-connector
    steps:
    - uses: actions/checkout@v4
    - run: wiz-semgrep-connector